CmsBundle\Entity\Accueil:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Artiste:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Partenaire:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Presse:
    properties:
        # ...
        file:
            - Image: ~


CmsBundle\Entity\Newsletter:
    properties:
        file:
            - File:
                maxSize: 2048k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: "Merci de proposer un fichier PDF valide"