user_artiste:
    path:     /artistes
    defaults: { _controller: CmsBundle:User:artistes }

user_commercant:
    path:     /commercants
    defaults: { _controller: CmsBundle:User:commercants }

user_partenaire:
    path:     /partenaires
    defaults: { _controller: CmsBundle:User:partenaires }

user_archive:
    path:     /archives
    defaults: { _controller: CmsBundle:User:archives }

user_presse:
    path:     /presses
    defaults: { _controller: CmsBundle:User:presses }

newsletter_adduser:
    path:     /abonnement
    defaults: { _controller: CmsBundle:AbonnementNewsletters:abonnement }

newsletter_desabonnement:
    path:     /desabonnement
    defaults: { _controller: CmsBundle:AbonnementNewsletters:desabonnement }